#+ summary: test
#+ endpoint: https://semanticweb.cs.vu.nl/dss/sparql
#+ tags: 
#+   - test 

SELECT ?s ?lab WHERE 
{
	?s rdf:type dss:Ship.
	?s rdfs:label ?lab.
	FILTER (str(?lab) = "Johanna")
}
LIMIT 10
